### ISSUE TITLE
Small versioning issue

### ISSUE THREAD

**Issue by tiernan7** [DNA-and-Natural-Algorithms-Group/KinDA#3]
The documentation lists that Python 3.9+ is required. However some of the code uses Union type annotation syntax which is only supported in python 3.10+. If you try to run the examples with 3.9, you get the following error:  line 321, in System
    def get_stats(self, obj: RestingSet | RestingSetReaction
TypeError: unsupported operand type(s) for |: 'type' and 'type'. A quick fix is to just update the documentation to require python 3.10+

**Comment by ntfrgl** [comment]
Thanks for pointing this out!
